### ISSUE TITLE
Post-processing?

### ISSUE THREAD

**Issue by markkrenek** [gonzalezreal/Groot#48]
I have situations where after Groot populates an NSManagedObject with data (be it a new instance or an existing instance) I need to do some post-processing of the object, like setting up some relationships that aren't described in the JSON. Is there any way to hook into right after Groot populates an NSManagedObject? This would be akin to JSONDictionaryTransformerName which lets you do some pre-processing.

**Comment by ManueGE** [comment]
I had to handle with this issue in some of my apps. This is the way I solved it. 

First, I create a `NSManagedObject` category with two methods:
````
+ (instancetype) grt_mergeObjectFromJSONDictionary:(NSDictionary *) dictionary
							inManagedObjectContext:(NSManagedObjectContext *)context
											 error:(NSError **) error;
+ (NSArray *) grt_mergeObjectsFromJSONArray:(NSArray *)array
					 inManagedObjectContext:(NSManagedObjectContext *)context
									  error:(NSError *__autoreleasing *)error;
````

In its implementation, I call the Groot methods.

When I want to parse a JSON, I use always this category instead of the **Groot** methods. If one of my entities needs a post-processing, I just override this methods and perform the post-process there. 

If you like this idea, I can provide the full code of the category.

**Comment by markkrenek** [comment]
Interesting. Those merge function are from an older version of Groot, right? I'm using GRTJSONSerialization.objectsWithEntityName to fire off a big chain of serializations which ultimately calls grt_serializeJSONDictionary for each managed object. I need to look into having my subclasses of NSManagedObject override grt_serializeJSONDictionary. I'm using Swift.

**Comment by gonzalezreal** [comment]
I would have thought that use case is covered by returning the serialized managed objects.
I will consider having methods that take a block for post-processing if that's not enough. Any other ideas are welcome.
